name: Python package

on: [push]

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest
    container:
      image: python:3.7-alpine
      volumes:
        - my_docker_volume:/opt/project
      options: --cpus 1
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip install --no-color -q poetry
          poetry config settings.virtualenvs.create false
          poetry install --no-dev --no-ansi -qn
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    name: Test with pytest
    runs-on: ubuntu-latest
    container:
      image: python:3.7-alpine
      volumes:
        - my_docker_volume:/opt/project
      options: --cpus 1
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip install --no-color -q poetry
          poetry config settings.virtualenvs.create false
          poetry install --no-ansi -qn
      - name: Test with pytest
        run: |
          pytest
